defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: openjdk:8-jdk
  environment:
    JVM_OPTS: -Xmx2048m
    GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Execute Gradle
          command: |
            if [ -z "$CIRCLE_TAG" ]; then
              echo "Circle tag is present (${CIRCLE_TAG}), buliding and publishing release..."
              echo "signing.keyId=${SIGNING_KEY}" >> "gradle.properties"
              echo "signing.password=${SIGNING_PASSWORD}" >> "gradle.properties"
              echo "signing.secretKeyRingFile=../maven.keystore" >> "gradle.properties"
              gpg --cipher-algo AES256 --yes --batch --passphrase=$ENC_FILE_KEY maven.keystore.gpg
              ./gradlew build publish -x jsBrowserTest --no-daemon
            else
              ./gradlew build -x jsBrowserTest --no-daemon
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Sonatype
          filters:
            tags:
              only: /.*/
